### ISSUE TITLE
アルファベットについて

### ISSUE THREAD

**Issue by kubo-aoi** [c0a2110686/ProjExD#4]
https://github.com/c0a2110686/ProjExD/blob/9a9c98931f4e5d070a874936270231c7b5836c35/ex01/alphabet.py#L20

アルファベットの文字数が分かってるときに限るコード（26のところ）だから、文字数が分からなくても実行できるといいなーとちょっと思いました。

**Comment by c0a2110686** [comment]
参考になった！
ありがとう
